#Install Cent OS
FROM centos:latest

RUN yum update -y
RUN yum install -y gcc-gfortran gdb make

#Copy Files
COPY Makefile run_fortran.sh SampleFortran.f90

# Compile code
WORKDIR /fortran/
RUN make SampleFortran

ENTRYPOINT ["./fortran.sh"]